### ISSUE TITLE
nuage_overcloud_full_patch.py

### ISSUE THREAD

**Issue by jfargen** [nuagenetworks/nuage-ospdirector#51] opened 2019-04-18 18:34 UTC
The package openstack-neutron-sriov-nic-agent in NUAGE_DEPENDENCIES has a dependency on openvswitch-2.9.0-83.el7fdp.1.x86_64. This results in the package openvswitch-2.9.0-83.el7fdp.1.x86_64 being installed, which conflicts with nuage-openvswitch.

Error: nuage-openvswitch conflicts with openvswitch-2.9.0-83.el7fdp.1.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
virt-customize: error: nuage_packages: command exited with an error

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
 
 exiting

Now, I will agree that it isn't necessarily an issue of the script, but the only fix I have at the moment is to remove the package openstack-neutron-sriov-nic-agent from the script. Either way the dependency of openstack-neutron-sriov-nic-agent needs to be changed from openvswitch to nuage-openvswitch.

**Comment by dttocs** [comment] 2019-05-07 22:14
Thanks for highlighting this - there are two problems I can see here:

1. integration scripts are unnecessarily installing openstack-neutron-sriov-nic-agent on the overcloud image - it should only be present in the Neutron container.
2. There is a chain of dependencies resulting in an attempt to install openvswitch-2.9.0-83.

For #1 your proposed approach of removing the package from the virt-customize is fine.

For #2, this is related to a change in latest RHEL 7.6 packages.  There is a issue with the latest RHEL 7.6 updates breaking Neutron with nuage due to changed dependencies for python-openvswitch.  It was caused byhttps://bugzilla.redhat.com/show_bug.cgi?id=1659163 which introduced this dependency.  Nuage plans to provide a Nuage-specific python-openvswitch which is not tightly coupled to a specific openswitch version, which will replace the upstream python-openvswitch package.

**Comment by sunny-verma** [comment] 2019-06-26 00:10
Thanks @jfargen . #67  should take care of that. Let me know if you still see that issue.

**Comment by sunny-verma** [comment] 2019-07-15 16:33
I will close this issue as it's being resolved in the OSPD13 branch. 
@jfargen

**Closed by sunny-verma** 2019-07-15 16:33 UTC
